---
  - name: ENable Nginx package
    become: yes
    shell: "amazon-linux-extras enable nginx1"

  - name: Install Nginx
    become: yes
    package:
      name: nginx
      state: present

  - name: Copy Nginx Config file
    become: yes
    template:
      src: default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      owner: root
      group: root
      mode: '644'

  - name: Copy Index.html
    become: yes
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html
      owner: root
      group: root
      mode: '644'
  - name: Copy Certificates
    become: yes
    copy:
      src: nginx.crt
      dest: "{{ cert_file }}"
  - name: Copy Private key
    become: yes
    copy:
      src: nginx.key
      dest: "{{ key_file }}"

  - name: Restart Nginx
    become: yes
    systemd:
      name: nginx
      state: restarted

  - name: Check Nginx Status
    become: yes
    shell: "systemctl status nginx"
    args:
      executable: /bin/bash
