pipeline {
  agent {
    label 'master'
  }
  stages {
    stage("Deploy Application") {
      steps {
        dir("playbooks/install_apps"){
          ansiColor('xterm') {
            ansiblePlaybook(
                playbook: 'install_maven_web_app.yml'',
                inventory: '../../env/dev/dev.ini',
                credentialsId: 'devops',
                colorized: true)
            }
          }
        }
      }
  }
}
