pipeline {
  agent {
    label 'master'
  }
  parameters {
    string(name:'APP_TAG', defaultValue:'NONE', description: 'App version')
  }
  stages {
    stage("Deploy Application") {
      steps {
        dir("playbooks/install_apps"){
          ansiColor('xterm') {
            ansiblePlaybook(
                playbook: 'install_maven_web_app.yml',
                inventory: '../../env/dev/dev.ini',
                credentialsId: 'devops',
                extras: '-e tag="${APP_TAG}"',
                colorized: true)
            }
          }
        }
      }
  }
}
